#!/bin/sh

while true ; do
  NETWORK=📶

  if systemctl status openvpn-toronto.service | grep 'Active: active' > /dev/null ; then
    NETWORK_COLOUR='darkred'
    NETWORK="$NETWORK 🕵️"
  else
    NETWORK_COLOUR='indigo'
  fi

  NETWORK="$NETWORK `nmcli -t -f GENERAL.CONNECTION device show wlp2s0 | cut -d : -f 2-`"
  NETWORK="$NETWORK (`nmcli -t -f IP4.ADDRESS device show wlp2s0 | grep -o '\([0-9]\+\.\)\{3\}[0-9]\+'`)"

  VOLUME=`pactl list sinks | grep '	Volume:' | grep -o '[0-9]\+%' | cut -d % -f 1 | head -n 1`

  if pactl list sinks | grep 'Active Port: analog-output-headphones' > /dev/null ; then
    AUDIO=🎧

    if pactl list sinks | grep 'Mute: yes' > /dev/null ; then
      AUDIO="$AUDIO 🔇"
    fi

  elif pactl list sinks | grep 'Mute: yes' > /dev/null ; then
    AUDIO=🔇
  elif [[ $VOLUME -le 0 ]] ; then
    AUDIO=🔈
  elif [[ $VOLUME -lt 50 ]] ; then
    AUDIO=🔉
  else
    AUDIO=🔊
  fi

  AUDIO="$AUDIO $VOLUME%"

  if [[ `cat /sys/class/power_supply/BAT0/status` = Discharging ]] ; then
    POWER=🔋
  else
    POWER=🔌
  fi

  POWER="$POWER `cat /sys/class/power_supply/BAT0/capacity`%"

  DATE=`date '+%a %b %d %Y %-I:%M:%S %p'`

  echo \
    "<span background=\"$NETWORK_COLOUR\"> $NETWORK </span>" \
    "<span background=\"darkblue\"> $AUDIO </span>" \
    "<span background=\"darkgreen\"> $POWER </span>" \
    "<span> $DATE </span>"

  sleep 1
done
