[colors.primary]
background = "#000000"
foreground = "#ffffff"

[font.normal]
family = "Noto Sans Mono"

[scrolling]
history = 100000

[shell]
args = ["-p", "--command", "zsh"]
program = "nix-shell"

[window]
opacity = 0.9
