[colors.primary]
background = "#000000"
foreground = "#ffffff"

[font.normal]
family = "Noto Sans Mono"

[mouse.hints.launcher]
args = ["--enable-features=UseOzonePlatform", "--ozone-platform=wayland", "--disable-gpu-memory-buffer-video-frames"]
program = "chromium"

[scrolling]
history = 100000

[shell]
args = ["-p", "--command", "zsh"]
program = "nix-shell"

[window]
opacity = 0.9
