version: "3"

# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    # ports:
    #   - "53:53/tcp"
    #   - "53:53/udp"
    #   - "67:67/udp"
    #   - "80:80/tcp"
    #   - "443:443/tcp"
    network_mode: host
    environment:
      TZ: 'America/Toronto'
      WEBPASSWORD: 'redacted'
    # Volumes store your data between container upgrades
    volumes:
      - './pihole/etc/pihole/:/etc/pihole/'
      - './pihole/etc/dnsmasq.d/:/etc/dnsmasq.d/'
      # run `touch ./pihole/var/log/pihole.log` first unless you like errors
      - './pihole/var/log/pihole.log:/var/log/pihole.log'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  znc:
    container_name: znc
    build: ./znc/build
    ports:
      - 8080:6667/tcp
    volumes:
      - ./znc/data:/znc-data
