# change prefix to ctrl+a
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# enable true colour for xterm-256color
set-option -ga terminal-overrides ",xterm-256color:Tc"

# vi navigation in copy mode
setw -g mode-keys vi

# more cool key combos
set -as terminal-features 'xterm*:extkeys'

# disable mouse
set -g mouse off

# 1-based indexing
set -g base-index 1
setw -g pane-base-index 1
